[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mlora"
version = "0.2.1.post1"
description = "A tool for fine-tuning large language models (LLMs) using the LoRA or QLoRA methods more efficiently."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2.1.2",
    "datasets",
    "evaluate",
    "accelerate",
    "transformers==4.38.2",
    "sentencepiece",
    "huggingface_hub",
    "scikit-learn",
]

[project.urls]
"Homepage" = "https://github.com/scukdde-llm/mlora"
"Bug Tracker" = "https://github.com/scukdde-llm/mlora/issues"

[tool.setuptools.packages.find]
include = ["mlora*"]
